"""End-to-end tests for the Streamlit application itself.

`tests/test_dashboard.py` covers the data layer. This file runs the actual app
through Streamlit's `AppTest` harness -- no browser, no server -- and asserts
every page renders.

That matters more than it sounds. The result tables and warehouse views are
generated by eight different modules, and a page that reads a column by a name
that module no longer writes fails only when someone opens it. These tests open
every page on every run.
"""

import pytest

from src import config

AppTest = pytest.importorskip("streamlit.testing.v1").AppTest

APP = str(config.PROJECT_ROOT / "app" / "dashboard.py")

PAGES = [
    "Overview",
    "Randomisation checks",
    "Treatment effects",
    "Who responds",
    "Targeting policy",
    "Profit and budget",
    "Explore the warehouse",
]


def open_page(name: str):
    """Start the app and navigate to one section."""
    app = AppTest.from_file(APP, default_timeout=180)
    app.run()
    app.sidebar.radio[0].set_value(name).run()
    return app


class TestEveryPageRenders:
    @pytest.mark.parametrize("page", PAGES)
    def test_renders_without_error(self, page):
        app = open_page(page)
        assert not app.exception, page

    @pytest.mark.parametrize("page", PAGES)
    def test_shows_a_chart(self, page):
        """Every section is meant to lead with a picture, not a table dump."""
        assert len(open_page(page).get("plotly_chart")) >= 1, page

    def test_the_sidebar_offers_every_page(self):
        app = AppTest.from_file(APP, default_timeout=180)
        app.run()
        assert app.sidebar.radio[0].options == PAGES


class TestProfitControls:
    """The one place the dashboard recomputes rather than reads."""

    def test_lowering_the_margin_lowers_reported_profit(self):
        app = open_page("Profit and budget")
        margin = app.slider[0]

        high = [m.value for m in margin.set_value(0.50).run().metric]
        low = [m.value for m in app.slider[0].set_value(0.10).run().metric]

        assert high != low

    def test_a_generous_margin_makes_both_campaigns_pay(self):
        """At a high enough margin the Womens campaign clears break-even too,
        which is the whole reason the assumption is exposed as a control."""
        app = open_page("Profit and budget")
        app.slider[0].set_value(0.60).run()

        verdicts = [m.delta for m in app.metric if m.delta]
        assert verdicts.count("pays for itself") == 2

    def test_a_thin_margin_leaves_neither_campaign_proven(self):
        app = open_page("Profit and budget")
        app.slider[0].set_value(0.05).run()

        verdicts = [m.delta for m in app.metric if m.delta]
        assert "pays for itself" not in verdicts

    def test_raising_the_send_cost_raises_the_break_even_bar(self):
        app = open_page("Profit and budget")
        cheap = app.slider[1].set_value(0.05).run().metric[0].value
        dear = app.slider[1].set_value(0.40).run().metric[0].value

        assert float(cheap.lstrip("$")) < float(dear.lstrip("$"))


class TestMissingResults:
    def test_a_page_without_its_results_explains_how_to_build_them(
        self, tmp_path, monkeypatch
    ):
        """A fresh clone has no generated results. Every page must degrade to
        an instruction rather than a traceback."""
        monkeypatch.setattr(config, "RESULTS_DIR", tmp_path)

        app = open_page("Targeting policy")
        assert not app.exception
        assert any("src.models.policy" in block.value for block in app.code)
